# it is best practice to keep your api keys secret. there is a file, 'api_key',
# in the .gitignore where you should paste your api key as plain text. 
# it will not (and should not) be added to any public git repository, and will remain unique for each machine
# new api keys can be generated at https://eln.ddomlab.org/ucp.php?tab=4
api_key_path: "api_key"
url: https://eln.ddomlab.org/api/v2